version: '3.7'

services:
  tensorflow:
    build: ./tensorflow
    container_name: tensorflow_container
    image: tensorflow/tensorflow:latest-gpu-jupyter
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/tf/notebooks
      - ./data:/tf/data
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_container
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns --host 0.0.0.0 --port 5000
